### ISSUE TITLE
.pyenv/shims isn't in $PATH

### ISSUE THREAD

**Issue by DanielRamosAcosta** [fisherman/pyenv#6]
I installed `pyenv` from [here](https://github.com/yyuu/pyenv-installer) and then I installed this `pyenv` using `fisher pyenv`. I can use `pyenv` command, the bin directory isn't being added to `PATH`.

![image](https://cloud.githubusercontent.com/assets/11427028/19145582/817eb7dc-8ba7-11e6-9dee-4ac25d011c87.png)
 What could I try to fix this?

**Comment by daenney** [comment]
Did you follow the instructions in the README?

> On Fish 2.3.0 and later support was introduced that automatically loads snippets in conf.d. However, these snippets are evaluated before your config.fish. If you're setting PYENV_ROOT in your config.fish to relocate your pyenv installation this will be evaluated after our plugin gets loaded and hence have no effect. In order to fix this you should drop a 000-env.fish file in your ~/.config/fish/conf.d folder which sets up your environment accordingly.

**Comment by daenney** [comment]
Looking at the code if `PYENV_ROOT` is not set we we always use `~/.pyenv` as the base dir and add `~/.pyenv/shims` to your PATH. Unless you've got something overriding that.

**Comment by DanielRamosAcosta** [comment]
What could be overriding PATH?

This is the list of plugins I have (`fisher ls`):
```
* metro			  fnm			  git_util		  humanize_duration	  menu			  pwd_is_home		  segment
  await			  get_file_age		  host_info		  last_job_id		  pwd_info		  pyenv
```

**Comment by daenney** [comment]
I don't know since I don't have access to your configuration. It could be any number of plugins or something you explicitly do in `config.fish` or one of the `conf.d/*.fish` snippets.

**Comment by DanielRamosAcosta** [comment]
I can't locate my `config.fish`... There isn't at `~/.config/fish/config.fish` :thinking:... And the only snippet appart from `pyenv` I have in `conf.d` is [`fnm.fish`](https://github.com/fisherman/fnm/blob/master/conf.d/fnm.fish)

**Comment by daenney** [comment]
Can you paste the output of running `env` in your shell?

**Comment by DanielRamosAcosta** [comment]
Here it is:

```
CLUTTER_IM_MODULE=xim
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-ey50JS6XB9,guid=ffa47490f2808be8b2831c3e57f79044
DEFAULTS_PATH=/usr/share/gconf/gnome.default.path
DESKTOP_SESSION=gnome
DISPLAY=:1
GDMSESSION=gnome
GJS_DEBUG_OUTPUT=stderr
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GTK_IM_MODULE=ibus
GTK_MODULES=gail:atk-bridge
HOME=/home/daniel
LANG=es_ES.UTF-8
LOGNAME=daniel
MANDATORY_PATH=/usr/share/gconf/gnome.mandatory.path
PATH=/home/daniel/.config/fnm/bin:/home/daniel/bin:/home/daniel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/daniel
QT4_IM_MODULE=xim
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
SESSION_MANAGER=local/daniel-lenovo:@/tmp/.ICE-unix/1321,unix/daniel-lenovo:/tmp/.ICE-unix/1321
SHELL=/usr/local/bin/fish
SHLVL=1
SSH_AGENT_PID=1390
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TERM=xterm-256color
USER=daniel
USERNAME=daniel
VTE_VERSION=4205
WINDOWID=29360134
WINDOWPATH=2
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-gnome:/etc/xdg
XDG_CURRENT_DESKTOP=GNOME
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_ID=1
XDG_SESSION_TYPE=x11
XDG_VTNR=2
XMODIFIERS=@im=ibus
```

**Comment by daenney** [comment]
Mmm, doesn't look like the plugin got so much as loaded.

- What version of fish shell are you on?
- Did you install Fisherman or Fin?
- Do you have a `~/.config/fish/functions/fisherman.fish` or `fin.fish`?

**Comment by DanielRamosAcosta** [comment]
* `fish --version`: `fish, version 2.3.1-563-g204e791`
*  I use fisherman as my plugin manager
* I haven't any `fisherman.fish` nor `fin.fish` at `~/.config/fish/functions`, but I have a `fisher.fish`
* `fisher -v`: `fisherman version 2.10.0 ~/.config/fish/functions/fisher.fish`

**Comment by daenney** [comment]
Well, that all seems right.

Do you see a symlink for `pyenv` in `~/.config/fish/conf.d`?

**Comment by DanielRamosAcosta** [comment]
Yup, it's pointing to `~/.config/fisherman/pyenv/conf.d/pyenv.fish`, that is [this file](https://raw.githubusercontent.com/fisherman/pyenv/master/conf.d/pyenv.fish)

**Comment by daenney** [comment]
Okay, eh, then everything should work. And you actually have a `~/.pyenv` which contains a `~/.pyenv/shims`? The `shims` directory usually only gets created once you've installed at least one Python version with pyenv but other than that this should work.

**Comment by DanielRamosAcosta** [comment]
Yes I have it, here are the contents:
```
> ll ~/.pyenv/
total 96K
drwxrwxr-x 2 daniel daniel 4,0K oct  6 08:40 bin/
-rw-rw-r-- 1 daniel daniel  20K oct  6 08:40 CHANGELOG.md
-rw-rw-r-- 1 daniel daniel 7,4K oct  6 08:40 COMMANDS.md
drwxrwxr-x 2 daniel daniel 4,0K oct  6 08:40 completions/
-rw-rw-r-- 1 daniel daniel 3,4K oct  6 08:40 CONDUCT.md
drwxrwxr-x 2 daniel daniel 4,0K oct  6 08:40 libexec/
-rw-rw-r-- 1 daniel daniel 1,1K oct  6 08:40 LICENSE
-rw-rw-r-- 1 daniel daniel  285 oct  6 08:40 Makefile
drwxrwxr-x 8 daniel daniel 4,0K oct  6 08:40 plugins/
drwxrwxr-x 4 daniel daniel 4,0K oct  6 08:40 pyenv.d/
-rw-rw-r-- 1 daniel daniel  14K oct  6 08:40 README.md
drwxrwxr-x 2 daniel daniel 4,0K oct  6 09:38 shims/
drwxrwxr-x 2 daniel daniel 4,0K oct  6 08:40 src/
drwxrwxr-x 3 daniel daniel 4,0K oct  6 08:40 test/
-rw-rw-r-- 1 daniel daniel    6 oct  6 09:23 version
drwxrwxr-x 3 daniel daniel 4,0K oct  6 08:54 versions/
> ll ~/.pyenv/shims/
total 68K
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 2to3*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 easy_install*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 easy_install-2.7*
-rwxrwxr-x 1 daniel daniel 404 oct  6 09:38 f2py*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 idle*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 pip*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 pip2*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 pip2.7*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 pydoc*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 python*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 python2*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 python2.7*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 python2.7-config*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 python2-config*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 python-config*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 smtpd.py*
-rwxrwxr-x 1 daniel daniel 404 oct  6 08:55 wheel*
```

And `pyenv rehash` gives me an error in line 9 saying that `command` can't find `pyenv`. Maybe the error is here? Now is like I haven't installed `pyenv`, but in my first comment did work... :confused: . I installed it with [`pyenv-installer`](https://github.com/yyuu/pyenv-installer#github-way-recommended), is that correct?

**Comment by daenney** [comment]
Mmm OK, so that would be a problem. If it says that it can't find the pyenv command it means it didn't end up inside your `$PATH`.

Looking at your PATH: `PATH=/home/daniel/.config/fnm/bin:/home/daniel/bin:/home/daniel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin` it doesn't look like `.pyenv/bin` is in there, so that's probably why the plugin isn't working, it's not seeing pyenv as installed.

**Comment by DanielRamosAcosta** [comment]
How could I get into `$PATH`? I don't know how to get it to work :cry:

**Comment by daenney** [comment]
How did you get things like `/usr/local/sbin` in your path? They're normally not there by default.

**Comment by DanielRamosAcosta** [comment]
Well... I don't know, but I haven't added them manually that's sure.

**Comment by daenney** [comment]
So the usual way of doing this for Fish 2.3+ would be to have a file of the sort `~/.config/fish/conf.d/000-env.fish` containing something like this:

```
set -x PATH $HOME/.pyenv/bin $PATH
```

**Comment by DanielRamosAcosta** [comment]
Yes! now it works! :smile: thanks you so much! I would recommend to add this command to the [README.md](https://github.com/fisherman/pyenv/blob/master/README.md) and put it a bit clearer.

Again, thanks you so much.

**Comment by daenney** [comment]
It's not really something that should be in the README, it's something the pyenv-installer or whatever installation method you used should've done for you or told you about. We can't find binaries that aren't on the PATH.

But I'll add a caveat anyways.
