### ISSUE TITLE
Python Version Isn't Set?

### ISSUE THREAD

**Issue by rdegges** [fisherman/pyenv#9]
Hey! I'm a new fish shell user, so I apolgize if this is a noob question.

I've installed pyenv via fisherman, and everything works with one exception: using `pyenv global 3.6.3` has no effect on my default python version in the shell.

For instance, if I run `pyenv global` I see the correct version (3.6.3) being returned, but when I run `python --version` on the CLI, I see `Python 2.7.14` (my system version).

I've installed this tool as instructed. Here's my `~/.config/fish/conf.d/000-env.fish` file:

```
set -x PYENV_ROOT $HOME/.pyenv
set -x PATH $PYENV_ROOT/bin $PATH
```

Any suggestions of what I might be missing?

**Comment by daenney** [comment]
Have you tried running a `pyenv rehash`?

**Comment by daenney** [comment]
Also note you'll need to spawn a new shell for the changes to `PATH` to get picked up.

**Comment by jimmyhuco** [comment]
I think you should `set -U fish_user_paths $PYENV_ROOT/shims $fish_user_paths`

include $PYENV_ROOT/shims to your $PATH

**Comment by rdegges** [comment]
So, quick update. I got this working after nuking my shell process. Sorry about that.

**Comment by daenney** [comment]
Awesome.
And no, you shouldn't have to manually add the shims to your PATH, the plugin takes care of that: https://github.com/fisherman/pyenv/blob/master/conf.d/pyenv.fish#L15-L18

**Comment by jimmyhuco** [comment]
@daenney you're right.

I just open terminal as non login.

**Comment by devxpy** [comment]
@daenney  i think this behaviour is observed because fish says its a non-login shell even though it clearly is.

**Comment by devxpy** [comment]
```
~ chsh
Password: 
Changing the login shell for dev
Enter the new value, or press ENTER for the default
	Login Shell [/usr/bin/fish]: 
~ status             
This is not a login shell
```
